version: "3"
services:
  app:
    container_name: machtwatch-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - machtwatch-network

  db:
    container_name: machtwatch-db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./deploy/db_data/:/var/lib/mysql
      - ./database/schema:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - machtwatch-network

volumes:
  db_data:
networks:
  machtwatch-network:
    driver: bridge